mysql_db_name = 'datn'
mysql_user = 'root'
mysql_pass = '1234'
mysql_host = '127.0.0.1'
mysql_port = '3306'
tesseract_OCR = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
watermark_img_path = 'static/watermark/watermark.png'  # Replace BASE_DIR with your project's base directory path
mail_username = 'viet6112001@gmail.com'
mail_password = 'tioj goil gxrr xbjr'
mail_port = 587
mail_use_ssl = False
mail_use_tls = True
thumb_size = 1920
thumbs_dir = 'thumbnails'