mysql_db_name = 'vietmcq'
mysql_user = 'root'
mysql_pass = 'Thai123h.'
mysql_host = '127.0.0.1'
mysql_port = '3306'
tesseract_OCR = r"/usr/bin/tesseract"
watermark_img_path = 'static/watermark/watermark.png'  # Replace BASE_DIR with your project's base directory path
mail_username = 'viet6112001@gmail.com'
mail_password = 'tioj goil gxrr xbjr'
mail_port = 587
mail_use_ssl = False
mail_use_tls = True
thumb_size = 1920
thumbs_dir = 'thumbnails'
run_port = 8080
log_file = 'logs/vietmcq.log'
