# Generated by Django 4.2.11 on 2024-04-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_ocr_value', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('normalized_value', models.TextField(blank=True, null=True)),
                ('box', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=127)),
                ('extension', models.CharField(blank=True, max_length=127, null=True)),
                ('image', models.ImageField(upload_to='origin')),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('cau_hoi', 'cau_hoi'), ('cau_tra_loi', 'cau_tra_loi'), ('dap_an', 'dap_an')], default='cau_tra_loi', max_length=27)),
                ('box', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='question')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='api.file')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_ocr_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('cau_hoi', 'cau_hoi'), ('cau_tra_loi', 'cau_tra_loi'), ('dap_an', 'dap_an')], default='cau_tra_loi', max_length=27)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.data')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_data_set', to='api.question')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_set', to='api.submission'),
        ),
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_set', to='api.file'),
        ),
    ]
