# Generated by Django 4.2.11 on 2024-04-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_submission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(default='now', max_length=512),
            preserve_default=False,
        ),
    ]
