# Generated by Django 4.2.11 on 2024-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_questiondata_display_name_file_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='display_name',
        ),
        migrations.AddField(
            model_name='question',
            name='display_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
