# Generated by Django 4.2.11 on 2024-04-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_file_image_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='box',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='data',
            name='symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
