# Generated by Django 4.2.11 on 2024-04-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_questiondata_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='tag', max_length=127, unique=True),
            preserve_default=False,
        ),
    ]
