# Generated by Django 4.2.11 on 2024-04-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_data_symbol_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiondata",
            name="data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.data",
            ),
        ),
    ]
