# Generated by Django 4.2.11 on 2024-04-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='data',
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_set', to='api.file'),
        ),
    ]
