# Generated by Django 4.2.11 on 2024-04-28 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_questiondata_data_alter_question_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
