# Generated by Django 4.2.11 on 2024-04-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_submission_file_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="display_name",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
