# Generated by Django 4.2.11 on 2024-04-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_question_user"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["display_name"], name="question_display_043b54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["tag_name"], name="api_tag_tag_nam_da348b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "name"], name="auth_user_email_71d043_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="data",
            table="data",
        ),
        migrations.AlterModelTable(
            name="question",
            table="question",
        ),
        migrations.AlterModelTable(
            name="questiondata",
            table="question_data",
        ),
    ]
